# Generated by Django 5.0.1 on 2024-08-17 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatbot',
            name='user',
        ),
    ]
